/*
 * @(#)	2014-8-11
 * Copyright (c) 2014 @wutalk on github. All rights reserved.
 */
package sample;

import sample.stockService.StockQuote;
import sample.stockService.StockQuoteSoap;

/**
 * 1) generate client support code: <br/>
 * <code>wsimport -p sample.stockService -keep http://www.webservicex.net/stockquote.asmx?WSDL</code>
 * <br/>
 * 2) write this client code(classes in this package except this one are all generated by wsimport)
 * 
 * @author wutalk
 */
public class StockClient {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		StockQuote sq = new StockQuote();
		StockQuoteSoap soap = sq.getStockQuoteSoap();
		String quote = soap.getQuote("GOOG");
		System.out.println("GOOG: " + quote);
	}
	/*---
	 * a simple run:
	 * -Dhttp.proxyHost=10.144.1.10 -Dhttp.proxyPort=8080
	<StockQuotes>
		<Stock>
			<Symbol>GOOG</Symbol>
			<Last>568.77</Last>
			<Date>8/8/2014</Date>
			<Time>4:00pm</Time>
			<Change>+5.41</Change>
			<Open>564.00</Open>
			<High>570.25</High>
			<Low>560.35</Low>
			<Volume>1492491</Volume>
			<MktCap>384.7B</MktCap>
			<PreviousClose>563.36</PreviousClose>
			<PercentageChange>+0.96%</PercentageChange>
			<AnnRange>502.80 - 604.83</AnnRange>
			<Earns>19.30</Earns>
			<P-E>29.19</P-E>
			<Name>Google Inc.</Name>
		</Stock>
	</StockQuotes>
	 -*/
}
